### ISSUE TITLE
Should update to Ubuntu 14.04

### ISSUE THREAD

**Issue by hmic** [FriendsOfCake/vagrant-chef#19]
There are official trusty images available on https://vagrantcloud.com/ubuntu, ready to use:

```
vagrant box add ubuntu/trusty64
```

**Comment by dereuromark** [comment]
:+1:

**Comment by josegonzalez** [comment]
Already done in master: https://github.com/FriendsOfCake/vagrant-chef/commit/8185744a9edc170bc123ab92c5361c049e92b062
