### ISSUE TITLE
Error executing action `run` on resource 'execute[add-default-username]'

### ISSUE THREAD

**Issue by damianoporta** [FriendsOfCake/vagrant-chef#32]
Hello!
I am having problem installing vagrant-chef, please read the log below.
(I have tried using normal and root user)

$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'precise32'...
==> default: Matching MAC address for NAT networking...
==> default: Setting the name of the VM: crm_default_1421577683463_38111
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 => 2222 (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
    default: The guest additions on this VM do not match the installed version of
    default: VirtualBox! In most cases this is fine, but in rare cases it can
    default: prevent things such as shared folders from working properly. If you see
    default: shared folder errors, please make sure the guest additions within the
    default: virtual machine match the version of VirtualBox you have installed on
    default: your host and reload your VM.
    default: 
    default: Guest Additions Version: 4.2.0
    default: VirtualBox Version: 4.3
==> default: Configuring and enabling network interfaces...
==> default: Mounting shared folders...
    default: /vagrant => /home/damiano/lavoro/apps/crm
    default: /tmp/vagrant-chef-3/chef-solo-2/roles => /home/damiano/lavoro/apps/crm/cookbooks/roles
    default: /tmp/vagrant-chef-3/chef-solo-1/cookbooks => /home/damiano/lavoro/apps/crm/cookbooks
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: stdin: is not a tty
==> default: - setting up auto chdir on ssh
==> default: - updating deb repository
==> default: - installing build requirements
==> default: Preconfiguring packages ...
==> default: (Reading database ... 
==> default: 29361 files and directories currently installed.)
==> default: Preparing to replace libssl-dev 1.0.1-4ubuntu5.5 (using .../libssl-dev_1.0.1-4ubuntu5.21_i386.deb) ...
==> default: Unpacking replacement libssl-dev ...
==> default: Preparing to replace libssl1.0.0 1.0.1-4ubuntu5.5 (using .../libssl1.0.0_1.0.1-4ubuntu5.21_i386.deb) ...
==> default: Unpacking replacement libssl1.0.0 ...
==> default: Setting up libssl1.0.0 (1.0.1-4ubuntu5.21) ...
==> default: Processing triggers for libc-bin ...
==> default: ldconfig deferred processing now taking place
==> default: (Reading database ... 
==> default: 29361 files and directories currently installed.)
==> default: Preparing to replace libxml2 2.7.8.dfsg-5.1ubuntu4 (using .../libxml2_2.7.8.dfsg-5.1ubuntu4.11_i386.deb) ...
==> default: Unpacking replacement libxml2 ...
==> default: Selecting previously unselected package libxslt1.1.
==> default: Unpacking libxslt1.1 (from .../libxslt1.1_1.1.26-8ubuntu1.3_i386.deb) ...
==> default: Selecting previously unselected package libstdc++6-4.6-dev.
==> default: Unpacking libstdc++6-4.6-dev (from .../libstdc++6-4.6-dev_4.6.3-1ubuntu5_i386.deb) ...
==> default: Selecting previously unselected package g++-4.6.
==> default: Unpacking g++-4.6 (from .../g++-4.6_4.6.3-1ubuntu5_i386.deb) ...
==> default: Selecting previously unselected package g++.
==> default: Unpacking g++ (from .../g++_4%3a4.6.3-1ubuntu5_i386.deb) ...
==> default: Selecting previously unselected package make.
==> default: Unpacking make (from .../make_3.81-8.1ubuntu1.1_i386.deb) ...
==> default: Selecting previously unselected package libdpkg-perl.
==> default: Unpacking libdpkg-perl (from .../libdpkg-perl_1.16.1.2ubuntu7.5_all.deb) ...
==> default: Selecting previously unselected package patch.
==> default: Unpacking patch (from .../patch_2.6.1-3_i386.deb) ...
==> default: Selecting previously unselected package dpkg-dev.
==> default: Unpacking dpkg-dev (from .../dpkg-dev_1.16.1.2ubuntu7.5_all.deb) ...
==> default: Selecting previously unselected package build-essential.
==> default: Unpacking build-essential (from .../build-essential_11.5ubuntu2.1_i386.deb) ...
==> default: Selecting previously unselected package fakeroot.
==> default: Unpacking fakeroot (from .../fakeroot_1.18.2-1_i386.deb) ...
==> default: Selecting previously unselected package libalgorithm-diff-perl.
==> default: Unpacking libalgorithm-diff-perl (from .../libalgorithm-diff-perl_1.19.02-2_all.deb) ...
==> default: Selecting previously unselected package libalgorithm-diff-xs-perl.
==> default: Unpacking libalgorithm-diff-xs-perl (from .../libalgorithm-diff-xs-perl_0.04-2build2_i386.deb) ...
==> default: Selecting previously unselected package libalgorithm-merge-perl.
==> default: Unpacking libalgorithm-merge-perl (from .../libalgorithm-merge-perl_0.08-2_all.deb) ...
==> default: Selecting previously unselected package libxml2-dev.
==> default: Unpacking libxml2-dev (from .../libxml2-dev_2.7.8.dfsg-5.1ubuntu4.11_i386.deb) ...
==> default: Selecting previously unselected package libxslt1-dev.
==> default: Unpacking libxslt1-dev (from .../libxslt1-dev_1.1.26-8ubuntu1.3_i386.deb) ...
==> default: Selecting previously unselected package unzip.
==> default: Unpacking unzip (from .../unzip_6.0-4ubuntu2.1_i386.deb) ...
==> default: Processing triggers for man-db ...
==> default: Setting up libssl-dev (1.0.1-4ubuntu5.21) ...
==> default: Setting up libxml2 (2.7.8.dfsg-5.1ubuntu4.11) ...
==> default: Setting up libxslt1.1 (1.1.26-8ubuntu1.3) ...
==> default: Setting up make (3.81-8.1ubuntu1.1) ...
==> default: Setting up libdpkg-perl (1.16.1.2ubuntu7.5) ...
==> default: Setting up patch (2.6.1-3) ...
==> default: Setting up dpkg-dev (1.16.1.2ubuntu7.5) ...
==> default: Setting up fakeroot (1.18.2-1) ...
==> default: update-alternatives: 
==> default: using /usr/bin/fakeroot-sysv to provide /usr/bin/fakeroot (fakeroot) in auto mode.
==> default: Setting up libalgorithm-diff-perl (1.19.02-2) ...
==> default: Setting up libalgorithm-diff-xs-perl (0.04-2build2) ...
==> default: Setting up libalgorithm-merge-perl (0.08-2) ...
==> default: Setting up libxml2-dev (2.7.8.dfsg-5.1ubuntu4.11) ...
==> default: Setting up libxslt1-dev (1.1.26-8ubuntu1.3) ...
==> default: Setting up unzip (6.0-4ubuntu2.1) ...
==> default: Setting up libstdc++6-4.6-dev (4.6.3-1ubuntu5) ...
==> default: Setting up g++-4.6 (4.6.3-1ubuntu5) ...
==> default: Setting up g++ (4:4.6.3-1ubuntu5) ...
==> default: update-alternatives: 
==> default: using /usr/bin/g++ to provide /usr/bin/c++ (c++) in auto mode.
==> default: Setting up build-essential (11.5ubuntu2.1) ...
==> default: Processing triggers for libc-bin ...
==> default: ldconfig deferred processing now taking place
==> default: Selecting previously unselected package m4.
==> default: (Reading database ... 
==> default: 30745 files and directories currently installed.)
==> default: Unpacking m4 (from .../m4_1.4.16-2ubuntu1_i386.deb) ...
==> default: Selecting previously unselected package libfl-dev.
==> default: Unpacking libfl-dev (from .../libfl-dev_2.5.35-10ubuntu3_i386.deb) ...
==> default: Selecting previously unselected package flex.
==> default: Unpacking flex (from .../flex_2.5.35-10ubuntu3_i386.deb) ...
==> default: Selecting previously unselected package libltdl7.
==> default: Unpacking libltdl7 (from .../libltdl7_2.4.2-1ubuntu1_i386.deb) ...
==> default: Selecting previously unselected package autoconf.
==> default: Unpacking autoconf (from .../autoconf_2.68-1ubuntu2_all.deb) ...
==> default: Selecting previously unselected package autotools-dev.
==> default: Unpacking autotools-dev (from .../autotools-dev_20120210.1ubuntu1_all.deb) ...
==> default: Selecting previously unselected package automake.
==> default: Unpacking automake (from .../automake_1%3a1.11.3-1ubuntu2_all.deb) ...
==> default: Selecting previously unselected package binutils-doc.
==> default: Unpacking binutils-doc (from .../binutils-doc_2.22-6ubuntu1.1_all.deb) ...
==> default: Selecting previously unselected package libbison-dev.
==> default: Unpacking libbison-dev (from .../libbison-dev_1%3a2.5.dfsg-2.1_i386.deb) ...
==> default: Selecting previously unselected package bison.
==> default: Unpacking bison (from .../bison_1%3a2.5.dfsg-2.1_i386.deb) ...
==> default: Selecting previously unselected package libltdl-dev.
==> default: Unpacking libltdl-dev (from .../libltdl-dev_2.4.2-1ubuntu1_i386.deb) ...
==> default: Selecting previously unselected package libtool.
==> default: Unpacking libtool (from .../libtool_2.4.2-1ubuntu1_i386.deb) ...
==> default: Processing triggers for install-info ...
==> default: Processing triggers for man-db ...
==> default: Setting up m4 (1.4.16-2ubuntu1) ...
==> default: Setting up libfl-dev (2.5.35-10ubuntu3) ...
==> default: Setting up flex (2.5.35-10ubuntu3) ...
==> default: Setting up libltdl7 (2.4.2-1ubuntu1) ...
==> default: Setting up autoconf (2.68-1ubuntu2) ...
==> default: Setting up autotools-dev (20120210.1ubuntu1) ...
==> default: Setting up automake (1:1.11.3-1ubuntu2) ...
==> default: update-alternatives: 
==> default: using /usr/bin/automake-1.11 to provide /usr/bin/automake (automake) in auto mode.
==> default: Setting up binutils-doc (2.22-6ubuntu1.1) ...
==> default: Setting up libbison-dev (1:2.5.dfsg-2.1) ...
==> default: Setting up bison (1:2.5.dfsg-2.1) ...
==> default: update-alternatives: 
==> default: using /usr/bin/bison.yacc to provide /usr/bin/yacc (yacc) in auto mode.
==> default: Setting up libltdl-dev (2.4.2-1ubuntu1) ...
==> default: Setting up libtool (2.4.2-1ubuntu1) ...
==> default: Processing triggers for libc-bin ...
==> default: ldconfig deferred processing now taking place
==> default: Selecting previously unselected package libyaml-0-2.
==> default: (Reading database ... 
==> default: 31201 files and directories currently installed.)
==> default: Unpacking libyaml-0-2 (from .../libyaml-0-2_0.1.4-2ubuntu0.12.04.4_i386.deb) ...
==> default: Selecting previously unselected package libruby1.9.1.
==> default: Unpacking libruby1.9.1 (from .../libruby1.9.1_1.9.3.0-1ubuntu2.10_i386.deb) ...
==> default: Selecting previously unselected package ruby1.9.1.
==> default: Unpacking ruby1.9.1 (from .../ruby1.9.1_1.9.3.0-1ubuntu2.10_i386.deb) ...
==> default: Selecting previously unselected package ri1.9.1.
==> default: Unpacking ri1.9.1 (from .../ri1.9.1_1.9.3.0-1ubuntu2.10_all.deb) ...
==> default: Selecting previously unselected package ruby1.9.1-dev.
==> default: Unpacking ruby1.9.1-dev (from .../ruby1.9.1-dev_1.9.3.0-1ubuntu2.10_i386.deb) ...
==> default: Processing triggers for man-db ...
==> default: Setting up libyaml-0-2 (0.1.4-2ubuntu0.12.04.4) ...
==> default: Setting up libruby1.9.1 (1.9.3.0-1ubuntu2.10) ...
==> default: Setting up ruby1.9.1 (1.9.3.0-1ubuntu2.10) ...
==> default: update-alternatives: 
==> default: using /usr/bin/gem1.9.1 to provide /usr/bin/gem (gem) in auto mode.
==> default: update-alternatives: 
==> default: using /usr/bin/ruby1.9.1 to provide /usr/bin/ruby (ruby) in auto mode.
==> default: Setting up ri1.9.1 (1.9.3.0-1ubuntu2.10) ...
==> default: Setting up ruby1.9.1-dev (1.9.3.0-1ubuntu2.10) ...
==> default: Processing triggers for libc-bin ...
==> default: ldconfig deferred processing now taking place
==> default: Running provisioner: chef_solo...
Generating chef JSON and uploading...
==> default: Running chef-solo...
==> default: stdin: is not a tty
==> default: [2015-01-18T10:42:38+00:00] INFO: *** Chef 10.14.2 ***
==> default: [2015-01-18T10:42:38+00:00] INFO: Setting the run_list to ["role[vagrant]"] from JSON
==> default: [2015-01-18T10:42:38+00:00] INFO: Run List is [role[vagrant]]
==> default: [2015-01-18T10:42:38+00:00] INFO: Run List expands to [system::update, hostname::default, git::install, percona::install, postgresql::install, redis::install, memcached::install, nginx::server, ruby::install, php::install, cakephp::setup]
==> default: [2015-01-18T10:42:38+00:00] INFO: Starting Chef Run for precise32
==> default: [2015-01-18T10:42:38+00:00] INFO: Running start handlers
==> default: [2015-01-18T10:42:38+00:00] INFO: Start handlers complete.
==> default: [2015-01-18T10:42:38+00:00] INFO: execute[trigger apt-get update] ran successfully
==> default: [2015-01-18T10:42:38+00:00] INFO: execute[trigger apt-get update] sending run action to execute[apt-get update] (immediate)
==> default: [2015-01-18T10:42:43+00:00] INFO: execute[apt-get update] ran successfully
==> default: [2015-01-18T10:43:12+00:00] INFO: execute[request git key] ran successfully
==> default: [2015-01-18T10:43:12+00:00] INFO: execute[install git key] ran successfully
==> default: [2015-01-18T10:43:12+00:00] INFO: template[/etc/apt/sources.list.d/git.list] updated content
==> default: [2015-01-18T10:43:12+00:00] INFO: template[/etc/apt/sources.list.d/git.list] owner changed to 0
==> default: [2015-01-18T10:43:12+00:00] INFO: template[/etc/apt/sources.list.d/git.list] group changed to 0
==> default: [2015-01-18T10:43:12+00:00] INFO: template[/etc/apt/sources.list.d/git.list] mode changed to 644
==> default: [2015-01-18T10:43:12+00:00] INFO: template[/etc/apt/sources.list.d/git.list] sending run action to execute[apt-get update] (immediate)
==> default: [2015-01-18T10:43:17+00:00] INFO: execute[apt-get update] ran successfully
==> default: [2015-01-18T10:43:33+00:00] INFO: package[git] upgraded from uninstalled to 1:2.2.2-0ppa1~ubuntu12.04.1
==> default: [2015-01-18T10:43:34+00:00] INFO: execute[request percona key] ran successfully
==> default: [2015-01-18T10:43:34+00:00] INFO: execute[install percona key] ran successfully
==> default: [2015-01-18T10:43:34+00:00] INFO: template[/etc/apt/sources.list.d/percona.list] updated content
==> default: [2015-01-18T10:43:34+00:00] INFO: template[/etc/apt/sources.list.d/percona.list] owner changed to 0
==> default: [2015-01-18T10:43:34+00:00] INFO: template[/etc/apt/sources.list.d/percona.list] group changed to 0
==> default: [2015-01-18T10:43:34+00:00] INFO: template[/etc/apt/sources.list.d/percona.list] mode changed to 644
==> default: [2015-01-18T10:43:34+00:00] INFO: template[/etc/apt/sources.list.d/percona.list] sending run action to execute[apt-get update] (immediate)
==> default: [2015-01-18T10:43:39+00:00] INFO: execute[apt-get update] ran successfully
==> default: [2015-01-18T10:43:39+00:00] INFO: file[/etc/apt/preferences.d/percona] owner changed to 0
==> default: [2015-01-18T10:43:39+00:00] INFO: file[/etc/apt/preferences.d/percona] group changed to 0
==> default: [2015-01-18T10:43:39+00:00] INFO: file[/etc/apt/preferences.d/percona] mode changed to 644
==> default: [2015-01-18T10:43:39+00:00] INFO: file[/etc/apt/preferences.d/percona] created file /etc/apt/preferences.d/percona
==> default: [2015-01-18T10:43:39+00:00] INFO: file[/etc/apt/preferences.d/ubuntu] owner changed to 0
==> default: [2015-01-18T10:43:39+00:00] INFO: file[/etc/apt/preferences.d/ubuntu] group changed to 0
==> default: [2015-01-18T10:43:39+00:00] INFO: file[/etc/apt/preferences.d/ubuntu] mode changed to 644
==> default: [2015-01-18T10:43:39+00:00] INFO: file[/etc/apt/preferences.d/ubuntu] created file /etc/apt/preferences.d/ubuntu
==> default: [2015-01-18T10:45:21+00:00] INFO: directory[/var/lib/mysql/binlogs] created directory /var/lib/mysql/binlogs
==> default: [2015-01-18T10:45:21+00:00] INFO: directory[/var/lib/mysql/binlogs] owner changed to 106
==> default: [2015-01-18T10:45:21+00:00] INFO: directory[/var/lib/mysql/binlogs] group changed to 111
==> default: [2015-01-18T10:45:21+00:00] INFO: directory[/var/lib/mysql/binlogs] mode changed to 755
==> default: [2015-01-18T10:45:29+00:00] INFO: package[xtrabackup] upgraded from uninstalled to 2.2.8-5059-1.precise
==> default: [2015-01-18T10:45:29+00:00] INFO: execute[set-mysql-root] ran successfully
==> default: [2015-01-18T10:45:30+00:00] INFO: template[/etc/mysql/my.cnf] updated content
==> default: [2015-01-18T10:45:30+00:00] INFO: template[/etc/mysql/my.cnf] sending restart action to service[mysql] (immediate)
==> default: [2015-01-18T10:45:36+00:00] INFO: service[mysql] restarted
==> default: [2015-01-18T10:45:36+00:00] INFO: execute[create-mysql-database-test_database_name] ran successfully
==> default: [2015-01-18T10:45:36+00:00] INFO: execute[create-mysql-database-database_name] ran successfully
==> default: [2015-01-18T10:45:36+00:00] INFO: execute[create-mysql-user-user] ran successfully
==> default: [2015-01-18T10:45:54+00:00] INFO: template[/postgresql.conf] updated content
==> default: [2015-01-18T10:45:54+00:00] INFO: template[/postgresql.conf] owner changed to 107
==> default: [2015-01-18T10:45:54+00:00] INFO: template[/postgresql.conf] group changed to 113
==> default: [2015-01-18T10:45:54+00:00] INFO: template[/postgresql.conf] mode changed to 600
==> default: [2015-01-18T10:45:54+00:00] INFO: template[/postgresql.conf] sending restart action to service[postgresql] (immediate)
==> default: [2015-01-18T10:45:58+00:00] INFO: service[postgresql] restarted
==> default: [2015-01-18T10:45:58+00:00] INFO: template[/pg_hba.conf] updated content
==> default: [2015-01-18T10:45:58+00:00] INFO: template[/pg_hba.conf] owner changed to 107
==> default: [2015-01-18T10:45:58+00:00] INFO: template[/pg_hba.conf] group changed to 113
==> default: [2015-01-18T10:45:58+00:00] INFO: template[/pg_hba.conf] mode changed to 600
==> default: [2015-01-18T10:45:58+00:00] INFO: template[/pg_hba.conf] sending restart action to service[postgresql] (immediate)
==> default: [2015-01-18T10:46:01+00:00] INFO: service[postgresql] restarted
==> default: [2015-01-18T10:46:01+00:00] INFO: template[/pg_hba.conf] sending run action to execute[add-default-username] (immediate)
==> default: ================================================================================
==> default: Error executing action `run` on resource 'execute[add-default-username]'
==> default: ================================================================================
==> default: Mixlib::ShellOut::ShellCommandFailed
==> default: ------------------------------------
==> default: 
==> default: Expected process to exit with [0], but received '1'
==> default: ---- Begin output of echo "CREATE USER username WITH ENCRYPTED PASSWORD 'password' CREATEDB;" | psql
==> default: createdb username
==> default: touch /var/chef/postgres_default_username
==> default:  ----
==> default: STDOUT: CREATE ROLE
==> default: STDERR: touch: cannot touch `/var/chef/postgres_default_username': Permission denied
==> default: ---- End output of echo "CREATE USER username WITH ENCRYPTED PASSWORD 'password' CREATEDB;" | psql
==> default: createdb username
==> default: touch /var/chef/postgres_default_username
==> default:  ----
==> default: Ran echo "CREATE USER username WITH ENCRYPTED PASSWORD 'password' CREATEDB;" | psql
==> default: createdb username
==> default: touch /var/chef/postgres_default_username
==> default:  returned 1
==> default: 
==> default: Resource Declaration:
==> default: ---------------------
==> default: # In /tmp/vagrant-chef-3/chef-solo-1/cookbooks/postgresql/recipes/server.rb
==> default: 
==> default:  26: 
==> default:  27: execute "add-default-username" do
==> default:  28:   action :nothing
==> default:  29:   user 'postgres'
==> default:  30:   command <<-EOH
==> default:  31: echo "CREATE USER username WITH ENCRYPTED PASSWORD '#{node['postgresql']['password']['postgres']}' CREATEDB;" | psql
==> default:  32: createdb username
==> default:  33: touch /var/chef/postgres_default_username
==> default:  34:   EOH
==> default:  35:   creates "/var/chef/postgres_default_username"
==> default:  36: end
==> default:  37: 
==> default: 
==> default: Compiled Resource:
==> default: ------------------
==> default: # Declared in /tmp/vagrant-chef-3/chef-solo-1/cookbooks/postgresql/recipes/server.rb:27:in `from_file'
==> default: 
==> default: execute("add-default-username") do
==> default:   retry_delay 2
==> default:   user "postgres"
==> default:   returns 0
==> default:   command "echo \"CREATE USER username WITH ENCRYPTED PASSWORD 'password' CREATEDB;\" | psql\ncreatedb username\ntouch /var/chef/postgres_default_username\n"
==> default:   retries 0
==> default:   recipe_name "server"
==> default:   creates "/var/chef/postgres_default_username"
==> default:   action [:nothing]
==> default:   cookbook_name :postgresql
==> default:   backup 5
==> default: end
==> default: 
==> default: [2015-01-18T10:46:01+00:00] ERROR: Running exception handlers
==> default: [2015-01-18T10:46:01+00:00] ERROR: Exception handlers complete
==> default: [2015-01-18T10:46:01+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> default: [2015-01-18T10:46:01+00:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: execute[add-default-username] (postgresql::server line 27) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
==> default: ---- Begin output of echo "CREATE USER username WITH ENCRYPTED PASSWORD 'password' CREATEDB;" | psql
==> default: createdb username
==> default: touch /var/chef/postgres_default_username
==> default:  ----
==> default: STDOUT: CREATE ROLE
==> default: STDERR: touch: cannot touch `/var/chef/postgres_default_username': Permission denied
==> default: ---- End output of echo "CREATE USER username WITH ENCRYPTED PASSWORD 'password' CREATEDB;" | psql
==> default: createdb username
==> default: touch /var/chef/postgres_default_username
==> default:  ----
==> default: Ran echo "CREATE USER username WITH ENCRYPTED PASSWORD 'password' CREATEDB;" | psql
==> default: createdb username
==> default: touch /var/chef/postgres_default_username
==> default:  returned 1
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.

**Comment by khunjay** [comment]
Having a similar issue: 

=> default:
==> default:  ----
==> default: STDOUT: CREATE ROLE
==> default: STDERR: touch: cannot touch `/var/chef/postgres_default_username': Permission denied

**Comment by josegonzalez** [comment]
I'll take a look later today.

**Comment by josegonzalez** [comment]
This should be fixed in latest master, though you'll need to:

- `vagrant destroy -f`
- pull the latest changes
- `vagrant up`
