### ISSUE TITLE
Mcrypt not enabled?

### ISSUE THREAD

**Issue by davidyell** [FriendsOfCake/vagrant-chef#33]
So I've just downloaded and provisioned my VM, and I'm testing out Rocketeer to do deploys.

I'm getting an error that `mcrypt` isn't found. `The following extensions could not be found: mcrypt`

[Although I can see it in the list of php extensions](https://github.com/FriendsOfCake/vagrant-chef/blob/master/cookbooks/php/recipes/install.rb#L14). 

But doing `vagrant ssh` and `php -m` the module doesn't show up in the list. I think the configuration needs to be updated to enable the module.

**Comment by davidyell** [comment]
I solved this problem by creating a symlink.

```bash
ln -s /etc/php5/mods-available/mcrypt.ini /etc/php5/fpm/conf.d/mcrypt.ini
```

**Comment by josegonzalez** [comment]
Interesting, can you check if any others are missing from the list of installed vs enabled?

**Comment by jadb** [comment]
I remember Neon saying in the channel it was the only one among all modules.

**Comment by davidyell** [comment]
Sure, I'll take a look tomorrow for you.

**Comment by davidyell** [comment]
Looks to me like it's just mcrypt, by checking the `php -m` against `php/recipes/install.rb`
