### ISSUE TITLE
The box 'chef/ubuntu-14.04' could not be found

### ISSUE THREAD

**Issue by LarryTX** [FriendsOfCake/vagrant-chef#34]
When I do a vagrant up, the following error displays:

Bringing machine 'default' up with 'virtualbox' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
* The box 'chef/ubuntu-14.04' could not be found.

Any ideas what I might be doing wrong?

**Comment by josegonzalez** [comment]
What version of vagrant are you running?

**Comment by LarryTX** [comment]
I had Vagrant 1.4.2 installed. I didn't think it was all that old, but I upgraded to 1.7.2, and that seems to be working. I must say I'm impressed. It's an unbelievably long Vagrant script! But, it is working!

**Comment by josegonzalez** [comment]
Yeah, you need a more up to date vagrant version :)
