### ISSUE TITLE
Vagrant try to connect to wrong ip (127.0.0.1)

### ISSUE THREAD

**Issue by luke83** [FriendsOfCake/vagrant-chef#50]
With the last release 0.4.4 i got this after a correct installation:

```
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'bento/ubuntu-14.04' is up to date...
==> default: Resuming suspended VM...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    [...]
```

I can correctly connect to vagrant@192.168.13.37

**Comment by josegonzalez** [comment]
That isn't the wrong IP. Vagrant sets up a bridge on the host port 2222 to the vm port 22, which is why you are able to ssh in separately. Not sure why you are getting auth failures, as that sounds like a separate issue, likely related to bento/ubuntu-14.04.
