### ISSUE TITLE
Error on downloading box with vagrant 1.8.7 on macOS Sierra

### ISSUE THREAD

**Issue by carlchen1986** [FriendsOfCake/vagrant-chef#52]
After having cloned this git-rep and running the command "vagrant up" the terminal shows the error:

```
The box 'bento/ubuntu-14.04' could not be found or could not be accessed 
in the remote catalog. If this is a private box on HashiCorp's Atlas, 
please verify you're logged in via vagrant login. Also, please 
double-check the name. The expanded URL and error message are shown below:

URL: ["https://atlas.hashicorp.com/bento/ubuntu-14.04"]
```

The README says it should use "Trusty Tahr" which is not in the vagrant-file.

**Comment by josegonzalez** [comment]
That is definitely a box, and it's publicly available [here](https://atlas.hashicorp.com/bento/ubuntu-14.04).

Are you by any chance behind a corporate firewall or something that would block you from accessing urls there?

**Comment by carlchen1986** [comment]
No I am trying to access that from my laptop (Macbook Pro, macOS Sierra, Virtualbox 5.1.8, Vagrant 1.8.7)

**Comment by josegonzalez** [comment]
I can see it here:

![https://cl.ly/3r2k1N0f381Y](https://cl.ly/3r2k1N0f381Y/Image%202016-11-21%20at%2011.02.54%20AM.png)

Can you maybe describe your network connection? I just tried on a fresh laptop, seems to work for me.

For the record, `bento/ubuntu-14.04` *is* Trusty Tahr. Trusty Tahr is the codename for Ubuntu 14.04.

**Comment by carlchen1986** [comment]
my network connection is via WirelessLAN to the Router. From there a standard broadband connection to the world ;)

Using the browser is working fine as seen. I can also use Safari to open the link you have provided. 

Interestingly it is also not working when I only run `vagrant init bento/ubuntu-14.04; vagrant up --provider virtualbox`. Same error (or to be clear, no error message apart from not working):

```
The box 'bento/ubuntu-14.04' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://atlas.hashicorp.com/bento/ubuntu-14.04"]
Error: 
```

So obviously there is something not working with my laptop although this is a fresh installation.

**Comment by carlchen1986** [comment]
Found the error. Obviously it is a bug on Vagrant, descriptor in issue [#7970](https://github.com/mitchellh/vagrant/issues/7970)

After having applied the fix, it is downloading the box

**Comment by josegonzalez** [comment]
Sorry about that!
