### ISSUE TITLE
Unclear instructions in readme

### ISSUE THREAD

**Issue by jpeltoniemi** [FriendsOfCake/vagrant-chef#55]
I've been at this for a couple of hours now. First Percona wouldn't install(which caused the whole setup to abort) so I settled with default MySQL. Now that I finally have the machine running, I had quite the hard time figuring out the folder structure. It's in the readme, sure, but kind of buried(is db config really more important than putting your app in the right place?).

Next, I put FriendsOfCake/app-template under apps and got an error 500. Logs say it can't find CakePHP, so I checked what's wrong. Seems that the app template tries to look for Cake in a different directory. But never mind that, I was under the impression that CakePHP would be included(It's in the readme title + a CakePHP cookbook is included) but that doesn't seem to be the case after all.

I realise some if not most of these problems are due to me being new to Chef and perhaps not understanding the conventions used here. However the readme makes it seem like everything should work out-of box, especially when using the recommended app template and as suggested by the very noob-friendly section about running and stopping vagrant. As things are now, it's way easier to just install everything by hand on a vanilla ubuntu than to try to make sense of the multiple errors that come from following instructions.

**My suggestion** is to improve the readme to include ALL steps from provisioning to the point where you access a working CakePHP app through browser. Even a crude list of required commands is better than nothing.

**Comment by josegonzalez** [comment]
Ouch. The readme does include this information, but I'll update it to include screenshots that will be easier to follow.

The percona issue was just solved.
