### ISSUE TITLE
Over engineered vagrant setup

### ISSUE THREAD

**Issue by maxpaynestory** [FriendsOfCake/vagrant-chef#57]
This is the most over engineered vagrant setup i have seen inside my entire life. Homestead is even better than this setup. This vagrant setup even include XORG server which is for UI.

1 hour or installation time is pretty hectic.
If somebody just want to try cakephp he doesn't want 2 databases on it.

I could contribute to optimizing this vagrant setup and improve the installation time.

**Comment by josegonzalez** [comment]
Please consider making pull requests with any changes you think would benefit the community.

**Comment by HarderWork** [comment]
If you just want to test CakePHP out there are easier options. For me this box has been very helpful in my professional development. And having 2 db:s came in very handy when I migrated from MySQL to Postgres. So, even if it take a while to install [https://www.youtube.com/watch?v=ouYKeeTz7Yw&t=70](it's worth waiting for)
