### ISSUE TITLE
Permit multiple applications

### ISSUE THREAD

**Issue by AD7six** [FriendsOfCake/vagrant-chef#7]
There's only one application possible to install automatically, which means either:

 * users should create one vm per application
 * users should manipulate their VM manually (`vagrant ssh; su vagrant; sudo su; etc`)

The first point is problematic for anyone working regularly on multiple applications - they will at least be at risk of running out of memory; The second point will lead to users having virtual machines which may have been installed into a consistent state but at the time of having some kind of problem, be in an INconsistent state.

It would be logical to permit by default multiple applications (http hosts) to prevent problems or hacks as users grow past their first steps using this repo.

**Comment by luke83** [comment]
# use case
app1.dev.vagrant -> /vagrant/apps/app1/dev/current/webroot
app2.dev.vagrant -> /vagrant/apps/app2/dev/current/webroot
app1.prod.vagrant -> /vagrant/apps/app1/prod/current/webroot

# file hosts (windows)

Append this to ``C:\Windows\System32\drivers\etc\hosts``

```
# VAGRANT
192.168.13.37	app1.dev.vagrant
192.168.13.37	app2.dev.vagrant
192.168.13.37	app1.prod.vagrant 
```

# default nginx

Use this little script (during provision) to accomodate this situation:

```
if [ ! -f /etc/nginx/sites-available/default.dist ]; then
    sudo cp /etc/nginx/sites-available/default/etc/nginx/sites-available/default.dist
fi

(echo "server {
  listen 80;
  server_name ~^(www\.)?((?<sname>[^\.]+?)\.)?(?<sdep>[^\.]+?).vagrant$;
  root /vagrant/apps/\$sname/\$sdep/current/webroot;
  access_log /var/log/nginx/\$sname.\$sdep-access.log;

  index index.php index.html;

  add_header Access-Control-Allow-Origin *;

  location ~ /\.ht {
    deny all;
  }

  location ~ \.php$ {
    fastcgi_pass unix:/var/run/php5-fpm.sock;
    include fastcgi_params;
  }

  location / {
    try_files \$uri \$uri/ /index.php?\$args;
    expires max;
    access_log on;
  }

  location @fallback {
    root /etc/nginx/app;
    index index.html;
  }
}

server {
  listen 80;
  server_name www.app.dev;
  rewrite ^ http://app.dev\$uri permanent;
}") | sudo tee /etc/nginx/sites-available/default > /dev/null
sudo service nginx restart
```
