### ISSUE TITLE
Chrome 63 forces .dev domains to HTTPS

### ISSUE THREAD

**Issue by HarderWork** [FriendsOfCake/vagrant-chef#70]
A recent update to Chrome forces all http on .dev domains to redirect to https (https://ma.ttias.be/chrome-force-dev-domains-https-via-preloaded-hsts/)
This breaks all apps that are accessed by http://appname.dev 
Solutions:
- Add a self signed certificate to *.dev
- Use another suffix than .dev in the nginx conf
- Don't use Chrome for local development...

Thoughts on this?

**Comment by josegonzalez** [comment]
New suffix. .localhost maybe?

**Comment by HarderWork** [comment]
I made a quick test with .localhost, but get the problem with localhost being resolved to 127.0.0.1 before reaching my own entry in my local hosts file (on Mac).
In the article above he recommends using .test instead, linking to this https://en.wikipedia.org/wiki/.test
That works well on my machine.
It should basically do with changing /etc/nginx/sites-available/apps config file and update Readme.md.
I could make a pull request if you are busy.

**Comment by josegonzalez** [comment]
That works.
